// <auto-generated />
using System;
using API_entity.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_entity.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220224123811_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_entity.Models.skill", b =>
                {
                    b.Property<int>("pkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("pkid");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("API_entity.Models.washer", b =>
                {
                    b.Property<int>("pkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("pkid");

                    b.ToTable("washers");
                });

            modelBuilder.Entity("API_entity.Models.washer_skill", b =>
                {
                    b.Property<int>("pkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Skillpkid")
                        .HasColumnType("int");

                    b.Property<int>("skill_id")
                        .HasColumnType("int");

                    b.Property<int>("washer_id")
                        .HasColumnType("int");

                    b.HasKey("pkid");

                    b.HasIndex("Skillpkid");

                    b.HasIndex("washer_id");

                    b.ToTable("washers_skills");
                });

            modelBuilder.Entity("API_entity.Models.washer_skill", b =>
                {
                    b.HasOne("API_entity.Models.skill", "Skill")
                        .WithMany()
                        .HasForeignKey("Skillpkid");

                    b.HasOne("API_entity.Models.washer", "washer")
                        .WithMany()
                        .HasForeignKey("washer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("washer");
                });
#pragma warning restore 612, 618
        }
    }
}
